In [1]:
from pathlib import Path
from src.data_loader import load_all_dataset

data_dir = Path("../data/raw")

dataset = load_all_dataset(data_dir)

for name, df in dataset.items():
    print(name, df.shape)

FD001 (20631, 26)
FD002 (53759, 26)
FD003 (24720, 26)
FD004 (61249, 26)

In [1]:
from src.data_loader import load_all_dataset
from src.preprocessing import preprocess_pipeline
from pathlib import Path

data_dir = Path("../data/raw")
datasets = load_all_dataset(data_dir)

df = datasets["FD001"]

df_processed = preprocess_pipeline(df)

df_processed[["unit_id", "cycles", "RUL"]].head()

   unit_id  cycles  RUL
0        1       1  125
1        1       2  125
2        1       3  125
3        1       4  125
4        1       5  125

In [2]:
df_processed[df_processed["unit_id"] == 1].tail()

,unit_id,cycles,op_settings_1,op_settings_2,op_settings_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21,RUL
187,1,188,-0.0067,0.0003,100.0,518.67,643.75,1602.38,1422.78,14.62,...,2388.23,8117.69,8.5207,0.03,396,2388,100.0,38.51,22.9588,4
188,1,189,-0.0006,0.0002,100.0,518.67,644.18,1596.17,1428.01,14.62,...,2388.33,8117.51,8.5183,0.03,395,2388,100.0,38.48,23.1127,3
189,1,190,-0.0027,0.0001,100.0,518.67,643.64,1599.22,1425.95,14.62,...,2388.35,8112.58,8.5223,0.03,398,2388,100.0,38.49,23.0675,2
190,1,191,-0.0000,-0.0004,100.0,518.67,643.34,1602.36,1425.77,14.62,...,2388.30,8114.61,8.5174,0.03,394,2388,100.0,38.45,23.1295,1
191,1,192,0.0009,-0.0000,100.0,518.67,643.54,1601.41,1427.20,14.62,...,2388.32,8110.93,8.5113,0.03,396,2388,100.0,38.48,22.9649,0